//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARTERA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CARTERA()
        {
            this.PRESTAMOS = new HashSet<PRESTAMOS>();
            this.RETIROS = new HashSet<RETIROS>();
        }
    
        public double CAPITAL { get; set; }
        public double CAPITAL_CAJA { get; set; }
        public Nullable<double> CAPITAL_PRESTADO { get; set; }
        public Nullable<double> UTILIDADES { get; set; }
        public Nullable<double> UTILIDAD_CAJA { get; set; }
        public Nullable<double> UTILIDAD_PRESTADA { get; set; }
        public Nullable<double> SEGURO { get; set; }
        public double TOTAL_CARTERA { get; set; }
        public int ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMOS> PRESTAMOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RETIROS> RETIROS { get; set; }
    }
}
