//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLIENTES()
        {
            this.PAGOS = new HashSet<PAGOS>();
            this.PRESTAMOS = new HashSet<PRESTAMOS>();
        }
    
        public string ID { get; set; }
        public int DOCUMENTO_ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDOS { get; set; }
        public Nullable<int> DEPARTAMENTO_ID { get; set; }
        public Nullable<int> MUNICIPIO_ID { get; set; }
        public string DIRECCION_VIVIENDA { get; set; }
        public string DIRECCION_TRABAJO { get; set; }
        public string TELEFONO { get; set; }
        public string NOMBRES_CONTACTO { get; set; }
        public string APELLIDOS_CONTACTO { get; set; }
        public string TELEFONO_CONTACTO { get; set; }
    
        public virtual DEPARTAMENTOS DEPARTAMENTOS { get; set; }
        public virtual DOCUMENTOS DOCUMENTOS { get; set; }
        public virtual MUNICIPIOS MUNICIPIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS> PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMOS> PRESTAMOS { get; set; }
    }
}
