//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGOS
    {
        public string ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public double CANTIDAD { get; set; }
        public string USUARIO_ID { get; set; }
        public string PRESTAMOS_ID { get; set; }
        public string CLIENTE_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual PRESTAMOS PRESTAMOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
