//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRESTAMOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTAMOS()
        {
            this.PAGOS = new HashSet<PAGOS>();
        }
    
        public string ID { get; set; }
        public string CLIENTE_ID { get; set; }
        public double CANTIDAD { get; set; }
        public int TASA_INTERES { get; set; }
        public int TIEMPO { get; set; }
        public int MODALIDAD_ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<double> AMORTIZACION { get; set; }
        public double SALDO { get; set; }
        public int CANTIDAD_CUOTAS { get; set; }
        public int CUOTAS_PAGADAS { get; set; }
        public int CUOTAS_POR_PAGAR { get; set; }
        public Nullable<double> SALDO_MORA { get; set; }
        public string USUARIO_ID { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<int> CARTERA_ID { get; set; }
    
        public virtual CARTERA CARTERA { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual MODALIDAD_PAGO MODALIDAD_PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS> PAGOS { get; set; }
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
