//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RETIROS
    {
        public string ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public double CANTIDAD { get; set; }
        public string DESCRIPCION { get; set; }
        public int CARTERA_ID { get; set; }
    
        public virtual CARTERA CARTERA { get; set; }
    }
}
