//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cartera_Facil.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USUARIOS()
        {
            this.PAGOS = new HashSet<PAGOS>();
            this.PRESTAMOS = new HashSet<PRESTAMOS>();
        }
    
        public string ID { get; set; }
        public int DOCUMENTO_ID { get; set; }
        public string NOMBRES { get; set; }
        public string APELLIDO { get; set; }
        public Nullable<int> DEPARTAMENTO_ID { get; set; }
        public Nullable<int> MUNICIPIO_ID { get; set; }
        public string DIRECCION { get; set; }
        public int CARGO_ID { get; set; }
        public byte[] FOTO { get; set; }
        public string PASSWORD { get; set; }
        public string TELEFONO { get; set; }
        public string EMAIL { get; set; }
        public string HABILITADO { get; set; }
        public int ROL_ID { get; set; }
    
        public virtual CARGOS CARGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGOS> PAGOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMOS> PRESTAMOS { get; set; }
        public virtual ROLES ROLES { get; set; }
    }
}
